import './globals.css'
import { Figtree } from 'next/font/google'
import Sidebar from '@/components/Sidebar'

const font = Figtree({subsets: ['latin']})

export const metadata = {
  title: 'DashBoard',
  description: 'Generated by Next.js',
}
 
export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body className={`${font.className}`}>
        <Sidebar>
          {children}
        </Sidebar>
      </body>
    </html>
  )
}
